CREATE TABLE NHOMHANG (
    MaNhomHang CHAR(5) PRIMARY KEY,
    TenNhomHang VARCHAR(100) NOT NULL,
    MoTa VARCHAR(255)
);

CREATE TABLE SANPHAM (
    MaSanPham CHAR(6) PRIMARY KEY,
    TenSanPham VARCHAR(150) NOT NULL,
    MaNhomHang CHAR(5),
    ThuongHieu VARCHAR(100),
    MoTa VARCHAR(255),
    TrangThai VARCHAR(20) NOT NULL,
    FOREIGN KEY (MaNhomHang) REFERENCES NHOMHANG(MaNhomHang)
);

CREATE TABLE BIENTHESANPHAM (
    MaBienThe CHAR(8) PRIMARY KEY,
    MaSanPham CHAR(6),
    SKU VARCHAR(30) UNIQUE,
    MaVach VARCHAR(30),
    KichThuoc VARCHAR(20),
    MauSac VARCHAR(30),
    Logo VARCHAR(50),
    DonViTinh VARCHAR(20) NOT NULL,
    GiaVon DECIMAL(12,2) NOT NULL,
    GiaBan DECIMAL(12,2) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham)
);

CREATE TABLE CHINHANH (
    MaChiNhanh CHAR(5) PRIMARY KEY,
    TenChiNhanh VARCHAR(100) NOT NULL,
    LoaiChiNhanh VARCHAR(20) NOT NULL,
    DiaChi VARCHAR(255),
    SoDienThoai VARCHAR(15),
    TrangThai VARCHAR(20) NOT NULL
);

CREATE TABLE VAITRO (
    MaVaiTro CHAR(5) PRIMARY KEY,
    TenVaiTro VARCHAR(50) NOT NULL,
    MoTa VARCHAR(255)
);

CREATE TABLE NGUOIDUNG (
    MaNguoiDung CHAR(6) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    SoDienThoai VARCHAR(15),
    MaVaiTro CHAR(5),
    MaChiNhanh CHAR(5),
    TrangThai VARCHAR(20) NOT NULL,
    FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro),
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh)
);

CREATE TABLE NHACUNGCAP (
    MaNhaCungCap CHAR(6) PRIMARY KEY,
    TenNhaCungCap VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15),
    Email VARCHAR(100),
    DiaChi VARCHAR(255),
    TrangThai VARCHAR(20) NOT NULL
);

CREATE TABLE PHIEUNHAP (
    MaPhieuNhap CHAR(8) PRIMARY KEY,
    MaNhaCungCap CHAR(6),
    MaChiNhanh CHAR(5),
    NguoiTao CHAR(6),
    NgayNhap TIMESTAMP NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    GhiChu VARCHAR(255),
    FOREIGN KEY (MaNhaCungCap) REFERENCES NHACUNGCAP(MaNhaCungCap),
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    FOREIGN KEY (NguoiTao) REFERENCES NGUOIDUNG(MaNguoiDung)
);

CREATE TABLE CT_PHIEUNHAP (
    MaPhieuNhap CHAR(8),
    MaBienThe CHAR(8),
    SoLuongNhap INT NOT NULL,
    DonGiaNhap DECIMAL(12,2) NOT NULL,
    ThanhTien DECIMAL(14,2) NOT NULL,
    PRIMARY KEY (MaPhieuNhap, MaBienThe),
    FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAP(MaPhieuNhap),
    FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe)
);

CREATE TABLE TONKHO (
    MaTonKho CHAR(8) PRIMARY KEY,
    MaChiNhanh CHAR(5),
    MaBienThe CHAR(8),
    SoLuongTon INT NOT NULL,
    DinhMucToiThieu INT,
    DinhMucToiDa INT,
    LanCapNhatCuoi TIMESTAMP NOT NULL,
    UNIQUE (MaChiNhanh, MaBienThe),
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe)
);

CREATE TABLE LICHSUTONKHO (
    MaLichSu CHAR(10) PRIMARY KEY,
    MaChiNhanh CHAR(5),
    MaBienThe CHAR(8),
    LoaiGiaoDich VARCHAR(30) NOT NULL,
    LoaiThamChieu VARCHAR(30),
    MaThamChieu CHAR(10),
    SoLuongThayDoi INT NOT NULL,
    SoLuongSauThayDoi INT NOT NULL,
    NguoiThucHien CHAR(6),
    ThoiGian TIMESTAMP NOT NULL,
    GhiChu VARCHAR(255),
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe),
    FOREIGN KEY (NguoiThucHien) REFERENCES NGUOIDUNG(MaNguoiDung)
);

CREATE TABLE HOADON (
    MaHoaDon CHAR(8) PRIMARY KEY,
    MaChiNhanh CHAR(5),
    NguoiTao CHAR(6),
    NgayLap TIMESTAMP NOT NULL,
    PhuongThucThanhToan VARCHAR(30) NOT NULL,
    TongTien DECIMAL(14,2) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    GhiChu VARCHAR(255),
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    FOREIGN KEY (NguoiTao) REFERENCES NGUOIDUNG(MaNguoiDung)
);

CREATE TABLE CT_HOADON (
    MaHoaDon CHAR(8),
    MaBienThe CHAR(8),
    SoLuongBan INT NOT NULL,
    DonGiaBan DECIMAL(12,2) NOT NULL,
    ThanhTien DECIMAL(14,2) NOT NULL,
    PRIMARY KEY (MaHoaDon, MaBienThe),
    FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon),
    FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe)
);

CREATE TABLE PHIEUCHUYEN (
    MaPhieuChuyen CHAR(8) PRIMARY KEY,
    ChiNhanhDi CHAR(5),
    ChiNhanhDen CHAR(5),
    NguoiTao CHAR(6),
    NguoiDuyet CHAR(6),
    NgayChuyen TIMESTAMP NOT NULL,
    NgayNhan TIMESTAMP,
    TrangThai VARCHAR(20) NOT NULL,
    GhiChu VARCHAR(255),
    FOREIGN KEY (ChiNhanhDi) REFERENCES CHINHANH(MaChiNhanh),
    FOREIGN KEY (ChiNhanhDen) REFERENCES CHINHANH(MaChiNhanh),
    FOREIGN KEY (NguoiTao) REFERENCES NGUOIDUNG(MaNguoiDung),
    FOREIGN KEY (NguoiDuyet) REFERENCES NGUOIDUNG(MaNguoiDung)
);

CREATE TABLE CT_PHIEUCHUYEN (
    MaPhieuChuyen CHAR(8),
    MaBienThe CHAR(8),
    SoLuongChuyen INT NOT NULL,
    SoLuongNhan INT,
    PRIMARY KEY (MaPhieuChuyen, MaBienThe),
    FOREIGN KEY (MaPhieuChuyen) REFERENCES PHIEUCHUYEN(MaPhieuChuyen),
    FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe)
);

CREATE TABLE PHIEUKIEMKHO (
    MaPhieuKiemKho CHAR(8) PRIMARY KEY,
    MaChiNhanh CHAR(5),
    NguoiTao CHAR(6),
    NguoiCanBang CHAR(6),
    NgayTao TIMESTAMP NOT NULL,
    NgayCanBang TIMESTAMP,
    TrangThai VARCHAR(20) NOT NULL,
    GhiChu VARCHAR(255),
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    FOREIGN KEY (NguoiTao) REFERENCES NGUOIDUNG(MaNguoiDung),
    FOREIGN KEY (NguoiCanBang) REFERENCES NGUOIDUNG(MaNguoiDung)
);

CREATE TABLE CT_PHIEUKIEMKHO (
    MaPhieuKiemKho CHAR(8),
    MaBienThe CHAR(8),
    SoLuongHeThong INT NOT NULL,
    SoLuongThucTe INT NOT NULL,
    SoLuongChenhLech INT NOT NULL,
    PRIMARY KEY (MaPhieuKiemKho, MaBienThe),
    FOREIGN KEY (MaPhieuKiemKho) REFERENCES PHIEUKIEMKHO(MaPhieuKiemKho),
    FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe)
);