export const databaseContract = {
  views: {
    productSearch: "vw_product_search_catalog",
    posVariantStock: "vw_pos_variant_stock_catalog",
    productVariantCatalog: "vw_product_variant_catalog",
    stockByBranch: "vw_stock_by_branch",
    orderSummary: "vw_order_summary",
    revenueByChannel: "vw_revenue_by_channel",
  },
  tables: {
    product: "product",
    productVariant: "product_variant",
    stock: "stock",
    stockHistory: "stock_history",
    inventoryAllocation: "inventory_allocation",
    purchaseOrder: "purchase_order",
    transferOrder: "transfer_order",
    stockAdjustment: "stock_adjustment",
    orders: "orders",
    orderDetail: "order_detail",
    payment: "payment",
    customer: "customer",
    returnOrder: "return_order",
    salesChannel: "sales_channel",
    channelPrice: "channel_price",
    branch: "branch",
    supplier: "supplier",
    users: "users",
    role: "role",
  },
  rpc: {
    createOrder: "fn_create_order_app",
    createPurchaseOrder: "fn_create_purchase_order_app",
    createTransfer: "fn_create_transfer_app",
    createAdjustment: "fn_create_adjustment_app",
    confirmPurchaseOrder: "fn_confirm_purchase_order_app",
    shipTransfer: "fn_ship_transfer_order_app",
    receiveTransfer: "fn_receive_transfer_order_app",
    completeAdjustment: "fn_complete_stock_adjustment_app",
    createReturn: "fn_create_return_app",
    setInventoryAllocation: "fn_set_inventory_allocation_app",
    lowStockCursorReport: "fn_cursor_low_stock_report_app",
  },
} as const;

export const requiredDatabaseViews = Object.values(databaseContract.views);
export const requiredDatabaseRpc = Object.values(databaseContract.rpc);
